/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.DBConection;
import DTO.NhanVien;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class frmMain extends javax.swing.JFrame {
//public static DBConection connection = new DBConection();

    public static DBConection connection = new DBConection();
//Tạo 1 biến toàn cục để lưu quyền của người dùng đăng nhập
    public static int Quyen = 0;

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        new JDLChay(this, true).setVisible(true);
        new JDLDangNhap(this, true).setVisible(true); //Sau khi dispose jdlLogin

        switch (Quyen) {
            case 1:
                pnlNVHHNCC.setVisible(false);
                pnlSuDungDichVu.setVisible(true);
                pnlThoat.setVisible(true);
                pnlThongKe.setVisible(false);
                pnlThuDonvaBan.setVisible(false);
                pnlTKKL.setVisible(true);
                break;
            case 2:
                pnlNVHHNCC.setVisible(false);
                pnlSuDungDichVu.setVisible(true);
                pnlTKKL.setVisible(false);
                pnlThoat.setVisible(true);
                pnlThongKe.setVisible(true);
                pnlThuDonvaBan.setVisible(true);

                break;
            case 3:
                pnlNVHHNCC.setVisible(true);
                pnlSuDungDichVu.setVisible(true);
                pnlTKKL.setVisible(true);
                pnlThoat.setVisible(true);
                pnlThongKe.setVisible(true);
                pnlThuDonvaBan.setVisible(true);
                break;
            default:
                break;
        }
    }

    public static void ThongBao(String tieuDe, String Noidung) {
        JOptionPane.showMessageDialog(new JFrame(), Noidung,
                tieuDe, JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlThuDonvaBan = new javax.swing.JPanel();
        lblIconSanPham = new javax.swing.JLabel();
        lblSanPham = new javax.swing.JLabel();
        lblIconlBan = new javax.swing.JLabel();
        lblBan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlNVHHNCC = new javax.swing.JPanel();
        lbIconlNhanVien = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblIconPhieuNhap = new javax.swing.JLabel();
        lblPhieuNhap = new javax.swing.JLabel();
        lblIconNhaCungCap = new javax.swing.JLabel();
        lblNCC = new javax.swing.JLabel();
        pnlTKKL = new javax.swing.JPanel();
        lblIconKho = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        lblIconThongKe = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        pnlSuDungDichVu = new javax.swing.JPanel();
        lblIconSuDungDichVu = new javax.swing.JLabel();
        lblSuDungDichVu = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pnlThoat = new javax.swing.JPanel();
        lblIconthoat = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần Mềm Quản Lý Nhà Hàng");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(85, 78, 59));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(63, 0, 4), null, null));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(212, 216, 225));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/images/Cocktail_30px_1.png"))); // NOI18N
        jLabel5.setText("Phần Mềm Quản Lý Nhà Hàng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 238, -1));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 39, -1, -1));

        jPanel2.setBackground(new java.awt.Color(85, 78, 59));

        pnlThuDonvaBan.setBackground(new java.awt.Color(85, 78, 56));

        lblIconSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIconSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/images/Orange Juice_48px_1.png"))); // NOI18N
        lblIconSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconSanPhamMouseExited(evt);
            }
        });

        lblSanPham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSanPham.setForeground(new java.awt.Color(255, 255, 0));
        lblSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSanPham.setText("Sản Phẩm");
        lblSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSanPhamMouseClicked(evt);
            }
        });

        lblIconlBan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIconlBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconlBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/images/Restaurant Table_60px_2.png"))); // NOI18N
        lblIconlBan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconlBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconlBanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconlBanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconlBanMouseExited(evt);
            }
        });

        lblBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBan.setForeground(new java.awt.Color(255, 255, 0));
        lblBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBan.setText("Bàn");
        lblBan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanMouseClicked(evt);
            }
        });

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlThuDonvaBanLayout = new javax.swing.GroupLayout(pnlThuDonvaBan);
        pnlThuDonvaBan.setLayout(pnlThuDonvaBanLayout);
        pnlThuDonvaBanLayout.setHorizontalGroup(
            pnlThuDonvaBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThuDonvaBanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlThuDonvaBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSanPham))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pnlThuDonvaBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThuDonvaBanLayout.createSequentialGroup()
                        .addGroup(pnlThuDonvaBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIconlBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        pnlThuDonvaBanLayout.setVerticalGroup(
            pnlThuDonvaBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThuDonvaBanLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThuDonvaBanLayout.createSequentialGroup()
                .addGroup(pnlThuDonvaBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIconlBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThuDonvaBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBan)
                    .addComponent(lblSanPham))
                .addContainerGap())
        );

        pnlNVHHNCC.setBackground(new java.awt.Color(85, 78, 56));

        lbIconlNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIconlNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconlNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/images/Office-Customer-Male-Light-icon.png"))); // NOI18N
        lbIconlNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbIconlNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIconlNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbIconlNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconlNhanVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbIconlNhanVienMousePressed(evt);
            }
        });

        lblNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(255, 255, 0));
        lblNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanVien.setText("Nhân Viên");
        lblNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseClicked(evt);
            }
        });

        lblIconPhieuNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIconPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/images/Finance-Bill-icon.png"))); // NOI18N
        lblIconPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconPhieuNhapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconPhieuNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconPhieuNhapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIconPhieuNhapMousePressed(evt);
            }
        });

        lblPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhieuNhap.setForeground(new java.awt.Color(255, 255, 0));
        lblPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhieuNhap.setText("Phiếu Nhập");
        lblPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhieuNhapMouseClicked(evt);
            }
        });

        lblIconNhaCungCap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIconNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shop_48px.png"))); // NOI18N
        lblIconNhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconNhaCungCapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconNhaCungCapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconNhaCungCapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIconNhaCungCapMousePressed(evt);
            }
        });

        lblNCC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNCC.setForeground(new java.awt.Color(255, 255, 0));
        lblNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNCC.setText("NCC");
        lblNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNCCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNVHHNCCLayout = new javax.swing.GroupLayout(pnlNVHHNCC);
        pnlNVHHNCC.setLayout(pnlNVHHNCCLayout);
        pnlNVHHNCCLayout.setHorizontalGroup(
            pnlNVHHNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNVHHNCCLayout.createSequentialGroup()
                .addGroup(pnlNVHHNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbIconlNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(pnlNVHHNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhieuNhap))
                .addGap(35, 35, 35)
                .addGroup(pnlNVHHNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlNVHHNCCLayout.setVerticalGroup(
            pnlNVHHNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNVHHNCCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNVHHNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIconlNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIconNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlNVHHNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhanVien)
                    .addComponent(lblPhieuNhap)
                    .addComponent(lblNCC))
                .addContainerGap())
        );

        pnlTKKL.setBackground(new java.awt.Color(85, 78, 56));

        lblIconKho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIconKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/images/Groups-Meeting-Dark-icon.png"))); // NOI18N
        lblIconKho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconKhoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIconKhoMousePressed(evt);
            }
        });

        lblKhachHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 0));
        lblKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhachHang.setText("Khách Hàng");
        lblKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTKKLLayout = new javax.swing.GroupLayout(pnlTKKL);
        pnlTKKL.setLayout(pnlTKKLLayout);
        pnlTKKLLayout.setHorizontalGroup(
            pnlTKKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTKKLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTKKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconKho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTKKLLayout.setVerticalGroup(
            pnlTKKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTKKLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKhachHang)
                .addContainerGap())
        );

        pnlThongKe.setBackground(new java.awt.Color(85, 78, 56));

        lblIconThongKe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIconThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/images/Combo Chart_50px.png"))); // NOI18N
        lblIconThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIconThongKeMousePressed(evt);
            }
        });

        lblThongKe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(255, 255, 0));
        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setText("Thống Kê");
        lblThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(lblIconThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongKe)
                .addContainerGap())
        );

        pnlSuDungDichVu.setBackground(new java.awt.Color(85, 78, 56));

        lblIconSuDungDichVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIconSuDungDichVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconSuDungDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/images/Restaurant Menu_50px.png"))); // NOI18N
        lblIconSuDungDichVu.setToolTipText("Quản lí dịch vụ");
        lblIconSuDungDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconSuDungDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconSuDungDichVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconSuDungDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconSuDungDichVuMouseExited(evt);
            }
        });

        lblSuDungDichVu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSuDungDichVu.setForeground(new java.awt.Color(255, 255, 0));
        lblSuDungDichVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuDungDichVu.setText("Sử Dụng Dịch Vụ");
        lblSuDungDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSuDungDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSuDungDichVuMouseClicked(evt);
            }
        });

        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel24MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuDungDichVuLayout = new javax.swing.GroupLayout(pnlSuDungDichVu);
        pnlSuDungDichVu.setLayout(pnlSuDungDichVuLayout);
        pnlSuDungDichVuLayout.setHorizontalGroup(
            pnlSuDungDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuDungDichVuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblSuDungDichVu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuDungDichVuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuDungDichVuLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblIconSuDungDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSuDungDichVuLayout.setVerticalGroup(
            pnlSuDungDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuDungDichVuLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlSuDungDichVuLayout.createSequentialGroup()
                .addComponent(lblIconSuDungDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSuDungDichVu)
                .addContainerGap())
        );

        pnlThoat.setBackground(new java.awt.Color(85, 78, 56));

        lblIconthoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIconthoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/images/logout-icon.png"))); // NOI18N
        lblIconthoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconthoatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconthoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconthoatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIconthoatMousePressed(evt);
            }
        });

        lblThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(255, 255, 0));
        lblThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoat.setText("Thoát");
        lblThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlThoatLayout = new javax.swing.GroupLayout(pnlThoat);
        pnlThoat.setLayout(pnlThoatLayout);
        pnlThoatLayout.setHorizontalGroup(
            pnlThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThoatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(lblIconthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlThoatLayout.setVerticalGroup(
            pnlThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThoatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThoat)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlSuDungDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThuDonvaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNVHHNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTKKL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTKKL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNVHHNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlThuDonvaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSuDungDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(85, 78, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/images/45360647_576940566085297_3040522505501540352_n.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 125)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Korea");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 0));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Restaurant");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged

    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

    }//GEN-LAST:event_jPanel1MousePressed

    private void lblIconSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSanPhamMouseClicked
        clicksp();
    }//GEN-LAST:event_lblIconSanPhamMouseClicked
    public void clicksp() {
        frmSanPham frm = new frmSanPham();
        frm.setVisible(true);
    }
    private void lblIconlBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconlBanMouseClicked
        clickban();
    }//GEN-LAST:event_lblIconlBanMouseClicked
    public void clickban() {
        frmBanNgoi frm = new frmBanNgoi();
        frm.setVisible(true);
    }
    private void lblIconlBanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconlBanMouseEntered
        lblIconlBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Restaurant Table_60px.png")));
        lblIconlBan.setFont(new Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_lblIconlBanMouseEntered

    private void lblIconlBanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconlBanMouseExited
        lblIconlBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Restaurant Table_60px_2.png")));
        lblIconlBan.setFont(new Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_lblIconlBanMouseExited

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed

    }//GEN-LAST:event_jLabel10MousePressed

    private void lbIconlNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconlNhanVienMouseEntered

    }//GEN-LAST:event_lbIconlNhanVienMouseEntered

    private void lbIconlNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconlNhanVienMouseExited

    }//GEN-LAST:event_lbIconlNhanVienMouseExited

    private void lbIconlNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconlNhanVienMousePressed

    }//GEN-LAST:event_lbIconlNhanVienMousePressed

    private void lblIconPhieuNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuNhapMouseEntered

    }//GEN-LAST:event_lblIconPhieuNhapMouseEntered

    private void lblIconPhieuNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuNhapMouseExited

    }//GEN-LAST:event_lblIconPhieuNhapMouseExited

    private void lblIconPhieuNhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuNhapMousePressed

    }//GEN-LAST:event_lblIconPhieuNhapMousePressed

    private void lblIconNhaCungCapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhaCungCapMouseEntered
//        lblIconNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shop_40px.png")));
//        lblIconNhaCungCap.setFont(new Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_lblIconNhaCungCapMouseEntered

    private void lblIconNhaCungCapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhaCungCapMouseExited
//        lblIconNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shop_48px.png")));
//        lblIconNhaCungCap.setFont(new Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_lblIconNhaCungCapMouseExited

    private void lblIconNhaCungCapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhaCungCapMousePressed

    }//GEN-LAST:event_lblIconNhaCungCapMousePressed

    private void lblIconKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconKhoMouseEntered

    }//GEN-LAST:event_lblIconKhoMouseEntered

    private void lblIconKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconKhoMouseExited

    }//GEN-LAST:event_lblIconKhoMouseExited

    private void lblIconKhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconKhoMousePressed

    }//GEN-LAST:event_lblIconKhoMousePressed

    private void lblIconThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseEntered

    }//GEN-LAST:event_lblIconThongKeMouseEntered

    private void lblIconThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseExited

    }//GEN-LAST:event_lblIconThongKeMouseExited

    private void lblIconThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMousePressed

    }//GEN-LAST:event_lblIconThongKeMousePressed

    private void lblIconSuDungDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSuDungDichVuMouseClicked
        clickdv();
    }//GEN-LAST:event_lblIconSuDungDichVuMouseClicked

    private void lblIconSuDungDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSuDungDichVuMouseEntered
        hover();
    }//GEN-LAST:event_lblIconSuDungDichVuMouseEntered

    private void lblIconSuDungDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSuDungDichVuMouseExited
        lblIconSuDungDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Restaurant Menu_50px.png")));
        lblIconSuDungDichVu.setFont(new Font("Tahoma", Font.PLAIN, 12));

    }//GEN-LAST:event_lblIconSuDungDichVuMouseExited

    private void jLabel24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MousePressed

    private void lblIconthoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconthoatMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconthoatMouseEntered

    private void lblIconthoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconthoatMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconthoatMouseExited

    private void lblIconthoatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconthoatMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconthoatMousePressed

    private void lblIconPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuNhapMouseClicked
        clickpn();
    }//GEN-LAST:event_lblIconPhieuNhapMouseClicked
    public void clickpn() {
        frmPhieuNhap frm = new frmPhieuNhap();
        frm.setVisible(true);
    }
    private void lblIconNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhaCungCapMouseClicked
        clickncc();
    }//GEN-LAST:event_lblIconNhaCungCapMouseClicked
    public void clickncc() {
        frmNhaCungCap frm = new frmNhaCungCap();
        frm.setVisible(true);
    }
    private void lblIconthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconthoatMouseClicked
        thoat();
    }//GEN-LAST:event_lblIconthoatMouseClicked
    public void thoat() {
        int ketquasaukhibam = JOptionPane.showConfirmDialog(new JFrame(),
                "Thông Báo ! Bạn Có Muốn Thoát Không ?", //thông báo 
                "Escape Warning !", //tiêu đề  
                JOptionPane.YES_NO_OPTION, //lựa chọn 
                JOptionPane.WARNING_MESSAGE); // icon 
        if (ketquasaukhibam == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
    private void lbIconlNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconlNhanVienMouseClicked
        clicknv();
    }//GEN-LAST:event_lbIconlNhanVienMouseClicked
    public void clicknv() {
        frmNhanVien frm = new frmNhanVien();
        frm.setVisible(true);
    }
    private void lblIconKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconKhoMouseClicked
        clickkh();
    }//GEN-LAST:event_lblIconKhoMouseClicked
    public void clickkh() {
        frmKhachHang frm = new frmKhachHang();
        frm.setVisible(true);
    }
    private void lblIconThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseClicked
        clickthongke();
    }//GEN-LAST:event_lblIconThongKeMouseClicked
    public void clickthongke() {
        frmThongKe frm = new frmThongKe();
        frm.setVisible(true);
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int ketquasaukhibam = JOptionPane.showConfirmDialog(new JFrame(),
                "Bạn có muốn thoát chương trình ?", //thông báo 
                "Thông báo!", //tiêu đề  
                JOptionPane.YES_NO_OPTION, //lựa chọn 
                JOptionPane.WARNING_MESSAGE); // icon 

        if (ketquasaukhibam == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void lblIconSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSanPhamMouseEntered
        lblIconSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Orange Juices_48px.png")));
        lblIconSanPham.setFont(new Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_lblIconSanPhamMouseEntered

    private void lblIconSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSanPhamMouseExited
        lblIconSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Orange Juice_48px.png")));
        lblIconSanPham.setFont(new Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_lblIconSanPhamMouseExited

    private void lblSuDungDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuDungDichVuMouseClicked
        clickdv();
    }//GEN-LAST:event_lblSuDungDichVuMouseClicked

    private void lblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSanPhamMouseClicked
        clicksp();        // TODO add your handling code here:
    }//GEN-LAST:event_lblSanPhamMouseClicked

    private void lblBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanMouseClicked
        clickban();
    }//GEN-LAST:event_lblBanMouseClicked

    private void lblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseClicked
        clicknv();
    }//GEN-LAST:event_lblNhanVienMouseClicked

    private void lblPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuNhapMouseClicked
        clickpn();
    }//GEN-LAST:event_lblPhieuNhapMouseClicked

    private void lblNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNCCMouseClicked
        clickncc();
    }//GEN-LAST:event_lblNCCMouseClicked

    private void lblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseClicked
        clickkh();
    }//GEN-LAST:event_lblKhachHangMouseClicked

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        clickthongke();
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        thoat();
    }//GEN-LAST:event_lblThoatMouseClicked
    public void clickdv() {
        frmHoaDon frm = new frmHoaDon();
        frm.setVisible(true);
    }

    public void hover() {
        lblIconSuDungDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Restaurant Menu_50px_1.png")));
        lblIconSuDungDichVu.setFont(new Font("Tahoma", Font.BOLD, 12));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbIconlNhanVien;
    private javax.swing.JLabel lblBan;
    private javax.swing.JLabel lblIconKho;
    private javax.swing.JLabel lblIconNhaCungCap;
    private javax.swing.JLabel lblIconPhieuNhap;
    private javax.swing.JLabel lblIconSanPham;
    private javax.swing.JLabel lblIconSuDungDichVu;
    private javax.swing.JLabel lblIconThongKe;
    private javax.swing.JLabel lblIconlBan;
    private javax.swing.JLabel lblIconthoat;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblNCC;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblPhieuNhap;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblSuDungDichVu;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JPanel pnlNVHHNCC;
    private javax.swing.JPanel pnlSuDungDichVu;
    private javax.swing.JPanel pnlTKKL;
    private javax.swing.JPanel pnlThoat;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlThuDonvaBan;
    // End of variables declaration//GEN-END:variables
}
