/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author LENOVO
 */
public class pnlThongTinChiTietHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form pnlThongTinChiTietHoaDon
     */
    public pnlThongTinChiTietHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChuaThongTin = new javax.swing.JPanel();
        lblSoLuong = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        spnSoLuong = new javax.swing.JSpinner();
        txtGhiChu = new javax.swing.JTextField();
        btnMoiBanNhapSoLuong = new javax.swing.JButton();

        pnlChuaThongTin.setBackground(new java.awt.Color(255, 255, 0));

        lblSoLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSoLuong.setForeground(new java.awt.Color(204, 0, 0));
        lblSoLuong.setText("Số Lượng");

        lblGhiChu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(204, 0, 0));
        lblGhiChu.setText("Ghi Chú");

        spnSoLuong.setValue(1);

        btnMoiBanNhapSoLuong.setBackground(new java.awt.Color(0, 102, 255));
        btnMoiBanNhapSoLuong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoiBanNhapSoLuong.setForeground(new java.awt.Color(204, 0, 0));
        btnMoiBanNhapSoLuong.setText("Mời Bạn Nhập Số Lượng");

        javax.swing.GroupLayout pnlChuaThongTinLayout = new javax.swing.GroupLayout(pnlChuaThongTin);
        pnlChuaThongTin.setLayout(pnlChuaThongTinLayout);
        pnlChuaThongTinLayout.setHorizontalGroup(
            pnlChuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuaThongTinLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlChuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoLuong)
                    .addComponent(lblGhiChu))
                .addGap(18, 18, 18)
                .addGroup(pnlChuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChuaThongTinLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(btnMoiBanNhapSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        pnlChuaThongTinLayout.setVerticalGroup(
            pnlChuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuaThongTinLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnMoiBanNhapSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(pnlChuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuong)
                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlChuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhiChu)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChuaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChuaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoiBanNhapSoLuong;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JPanel pnlChuaThongTin;
    public static javax.swing.JSpinner spnSoLuong;
    public static javax.swing.JTextField txtGhiChu;
    // End of variables declaration//GEN-END:variables
}
